### ISSUE TITLE
KSR Marketing Website

### ISSUE THREAD

**Issue by peetucket** [sul-dlss-labs/ksr#28]

**Comment by cncoleman** [comment]
What is a marketing website?

**Comment by peetucket** [comment]
This is what the current website at ksr.stanford.edu hosted via GH pages was being called by the team.  This ticket is actually an "epic" ticket if we use Zenhub instead of Github projects (though to github it is a regular ticket with the "Epic" label).  

I'm completely open to new terminology, and reorganizing epics/milestones in whatever way helps us stay organized as a team.
