### ISSUE TITLE
Add Studies to Graph database structure

### ISSUE THREAD

**Issue by cncoleman** [sul-dlss-labs/ksr#33]
[Spreadsheet with studies](https://docs.google.com/spreadsheets/d/1aM7nnt8w1ipZE836eAjz2IZxZ2NqrViEpDEz9T4K0VI/edit#gid=754356943)

**Comment by gbasel** [comment]
Added all entries from the "STUDIES Policing Housing" tab from the above spreadsheet to a an [organized spreadsheet of documents](https://docs.google.com/spreadsheets/d/1prQ7DzDhhJM9RebVnCkzqWNIJDpdHxKO-99Z2Rpx1MA/edit?usp=sharing).

Added all studies from this list to this [spreadsheet ready to input to linkurious](https://docs.google.com/spreadsheets/d/15Ceb6wNHlX67sfqVMqSkcC0mNTzxROZCDjF2VzLF1n4/edit?usp=sharing).
