### ISSUE TITLE
Add Stephon Clark data links

### ISSUE THREAD

**Issue by peetucket** [sul-dlss-labs/ksr#8]
I hope we can add the Stephon Clark data links to the Timeline Page to show what we hope to acheive long-term.

Additionally, I created a generic slide listing "samples" of upcoming topics.
If you all think the Search page is too busy, we can add it to the About Page.

Both sildes are on the 1 attached file.

I added the slides to Phase 3 Folder but Google looks uglier so I attached the PPT slide.

[Stephon Clark Data Interconnections SLide.pptx](https://github.com/sul-dlss-labs/srt/files/7033060/Stephon.Clark.Data.Interconnections.SLide.pptx)

**Comment by gbasel** [comment]
Added relevant info from above powerpoint to [this document](https://docs.google.com/document/d/1YdCfh_9Vw0L7B3dxGMQHLxQelCrDACTL7t61J8jL6gY/edit?usp=sharing). Lines crossed out in this document have been added to linkurious.
